Opal.queue(function(Opal) {/* Generated by Opal 1.8.2 */
  var $klass = Opal.klass, $return_val = Opal.return_val, $defs = Opal.defs, $nesting = [], nil = Opal.nil;

  return (function($base, $super) {
    var self = $klass($base, $super, 'Atome');

    
    return $defs(self, '$aui', $return_val("339f813253b453e292d57b97d0b433bcaea3694681984cecd4894c2f0b9f8d6a"))
  })($nesting[0], null)
});
