Opal.queue(function(Opal) {/* Generated by Opal 1.7.3 */
  var $klass = Opal.klass, $return_val = Opal.return_val, $defs = Opal.defs, $nesting = [], nil = Opal.nil;

  return (function($base, $super) {
    var self = $klass($base, $super, 'Atome');

    
    return $defs(self, '$mode', $return_val("tauri"))
  })($nesting[0], null)
});
