Opal.queue(function(Opal) {/* Generated by Opal 1.8.2 */
  var $klass = Opal.klass, $return_val = Opal.return_val, $defs = Opal.defs, $nesting = [], nil = Opal.nil;

  return (function($base, $super) {
    var self = $klass($base, $super, 'Atome');

    
    return $defs(self, '$aui', $return_val("bbdfe0e319012b7ca9c4947f7e771d04f672919b452846d39449cbfcbefe8574"))
  })($nesting[0], null)
});
