Opal.queue(function(Opal) {/* Generated by Opal 1.8.2 */
  var $klass = Opal.klass, $return_val = Opal.return_val, $defs = Opal.defs, $nesting = [], nil = Opal.nil;

  return (function($base, $super) {
    var self = $klass($base, $super, 'Atome');

    
    return $defs(self, '$aui', $return_val("7c911f3c07bb0c1126f02b303bc81c664af9162052cd971b5717873e4183767d"))
  })($nesting[0], null)
});
